# -*- coding: utf-8 -*-
"""Issue fully resolved.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SLaIz4w3SlGVX55I8PHjo4e-sIIxHfP5
"""

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from collections import Counter

"""### Removing "not" from stopwords dictionary and provide that dictionary as an argument to wordcloud api so that it will not get removed by that api"""

stopwords = set(STOPWORDS)
stopwords.remove("not")

words = ["not funny", "funny"]

"""### convert words list to dictionary with values and its occurences and give that as an input to wordcloud api"""

word_could_dict = Counter(words)
wordcloud = WordCloud(width=1000, height=500, stopwords=stopwords).generate_from_frequencies(word_could_dict)

"""### plotted wordcloud using matplotlib"""

plt.figure(figsize=(15, 8))
plt.imshow(wordcloud)
plt.axis("off")
plt.show()
plt.savefig('wordcloud.png', bbox_inches='tight')
plt.close()